  GNU nano 7.2                                                                         .github/workflows/first-workflow.yml *
name: Manual Hello World

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
